/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as KnowledgeBaseOfDigitalMarketingRouteImport } from './routes/knowledge-base-of-digital-marketing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesWebDesignRouteImport } from './routes/services.web-design'
import { Route as ServicesVirtualAssistanceRouteImport } from './routes/services.virtual-assistance'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesGraphicDesignRouteImport } from './routes/services.graphic-design'
import { Route as ServicesEcommerceRouteImport } from './routes/services.ecommerce'
import { Route as ServicesAmazonRouteImport } from './routes/services.amazon'
import { Route as ServicesAdsRouteImport } from './routes/services.ads'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseOfDigitalMarketingRoute =
  KnowledgeBaseOfDigitalMarketingRouteImport.update({
    id: '/knowledge-base-of-digital-marketing',
    path: '/knowledge-base-of-digital-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDesignRoute = ServicesWebDesignRouteImport.update({
  id: '/services/web-design',
  path: '/services/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVirtualAssistanceRoute =
  ServicesVirtualAssistanceRouteImport.update({
    id: '/services/virtual-assistance',
    path: '/services/virtual-assistance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGraphicDesignRoute = ServicesGraphicDesignRouteImport.update({
  id: '/services/graphic-design',
  path: '/services/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEcommerceRoute = ServicesEcommerceRouteImport.update({
  id: '/services/ecommerce',
  path: '/services/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAmazonRoute = ServicesAmazonRouteImport.update({
  id: '/services/amazon',
  path: '/services/amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdsRoute = ServicesAdsRouteImport.update({
  id: '/services/ads',
  path: '/services/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge-base-of-digital-marketing': typeof KnowledgeBaseOfDigitalMarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ads': typeof ServicesAdsRoute
  '/services/amazon': typeof ServicesAmazonRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/virtual-assistance': typeof ServicesVirtualAssistanceRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge-base-of-digital-marketing': typeof KnowledgeBaseOfDigitalMarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ads': typeof ServicesAdsRoute
  '/services/amazon': typeof ServicesAmazonRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/virtual-assistance': typeof ServicesVirtualAssistanceRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/knowledge-base-of-digital-marketing': typeof KnowledgeBaseOfDigitalMarketingRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/ads': typeof ServicesAdsRoute
  '/services/amazon': typeof ServicesAmazonRoute
  '/services/ecommerce': typeof ServicesEcommerceRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/virtual-assistance': typeof ServicesVirtualAssistanceRoute
  '/services/web-design': typeof ServicesWebDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/knowledge-base-of-digital-marketing'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/ads'
    | '/services/amazon'
    | '/services/ecommerce'
    | '/services/graphic-design'
    | '/services/seo'
    | '/services/virtual-assistance'
    | '/services/web-design'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/knowledge-base-of-digital-marketing'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/ads'
    | '/services/amazon'
    | '/services/ecommerce'
    | '/services/graphic-design'
    | '/services/seo'
    | '/services/virtual-assistance'
    | '/services/web-design'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/knowledge-base-of-digital-marketing'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/services/ads'
    | '/services/amazon'
    | '/services/ecommerce'
    | '/services/graphic-design'
    | '/services/seo'
    | '/services/virtual-assistance'
    | '/services/web-design'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  KnowledgeBaseOfDigitalMarketingRoute: typeof KnowledgeBaseOfDigitalMarketingRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesAdsRoute: typeof ServicesAdsRoute
  ServicesAmazonRoute: typeof ServicesAmazonRoute
  ServicesEcommerceRoute: typeof ServicesEcommerceRoute
  ServicesGraphicDesignRoute: typeof ServicesGraphicDesignRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesVirtualAssistanceRoute: typeof ServicesVirtualAssistanceRoute
  ServicesWebDesignRoute: typeof ServicesWebDesignRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base-of-digital-marketing': {
      id: '/knowledge-base-of-digital-marketing'
      path: '/knowledge-base-of-digital-marketing'
      fullPath: '/knowledge-base-of-digital-marketing'
      preLoaderRoute: typeof KnowledgeBaseOfDigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-design': {
      id: '/services/web-design'
      path: '/services/web-design'
      fullPath: '/services/web-design'
      preLoaderRoute: typeof ServicesWebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/virtual-assistance': {
      id: '/services/virtual-assistance'
      path: '/services/virtual-assistance'
      fullPath: '/services/virtual-assistance'
      preLoaderRoute: typeof ServicesVirtualAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/graphic-design': {
      id: '/services/graphic-design'
      path: '/services/graphic-design'
      fullPath: '/services/graphic-design'
      preLoaderRoute: typeof ServicesGraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ecommerce': {
      id: '/services/ecommerce'
      path: '/services/ecommerce'
      fullPath: '/services/ecommerce'
      preLoaderRoute: typeof ServicesEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/amazon': {
      id: '/services/amazon'
      path: '/services/amazon'
      fullPath: '/services/amazon'
      preLoaderRoute: typeof ServicesAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ads': {
      id: '/services/ads'
      path: '/services/ads'
      fullPath: '/services/ads'
      preLoaderRoute: typeof ServicesAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  KnowledgeBaseOfDigitalMarketingRoute: KnowledgeBaseOfDigitalMarketingRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesAdsRoute: ServicesAdsRoute,
  ServicesAmazonRoute: ServicesAmazonRoute,
  ServicesEcommerceRoute: ServicesEcommerceRoute,
  ServicesGraphicDesignRoute: ServicesGraphicDesignRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesVirtualAssistanceRoute: ServicesVirtualAssistanceRoute,
  ServicesWebDesignRoute: ServicesWebDesignRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
